packages:
  - packages/*

catalogs:
  default:
    '@bufbuild/buf': 1.57.0
    '@bufbuild/protobuf': 2.8.0
    '@bufbuild/protoc-gen-es': 2.8.0
    '@bufbuild/protoplugin': 2.9.0
    '@connectrpc/connect': 2.1.0
    '@connectrpc/connect-node': 2.1.0
    '@effect/language-service': 0.41.0
    '@effect/opentelemetry': 0.61.0
    '@effect/platform': 0.94.2
    '@effect/platform-node': 0.104.1
    '@effect/vitest': 0.19.4
    '@opentelemetry/api': 1.9.0
    '@opentelemetry/core': 2.0.0
    '@opentelemetry/sdk-trace-base': 2.0.0
    '@types/node': 24.4.0
    effect: 3.19.15
    tsx: 4.20.5
    typescript: 5.9.2
    vitest: 3.2.4
  peer:
    "@bufbuild/buf": ^1.57.0
    "@bufbuild/protoc-gen-es": ^2.8.0
    '@bufbuild/protobuf': ^2.8.0
    '@connectrpc/connect': ^2.1.0
    '@effect/opentelemetry': ^0.61.0
    effect: ^3.19.15
