packages:
  - packages/*

catalogs:
  default:
    '@bufbuild/buf': 1.57.0
    '@bufbuild/protobuf': 2.8.0
    '@bufbuild/protoc-gen-es': 2.8.0
    '@bufbuild/protoplugin': 2.9.0
    '@connectrpc/connect': 2.1.0
    '@connectrpc/connect-node': 2.1.0
    '@effect/language-service': 0.41.0
    '@effect/platform': 0.90.10
    '@effect/platform-node': 0.96.1
    '@effect/vitest': 0.19.4
    '@types/node': 24.4.0
    effect: 3.17.14
    tsx: 4.20.5
    typescript: 5.9.2
    vitest: 3.2.4
  peer:
    "@bufbuild/buf": ^1.57.0
    "@bufbuild/protoc-gen-es": ^2.8.0
    '@bufbuild/protobuf': ^2.8.0
    '@connectrpc/connect': ^2.1.0
    effect: ^3.17.0
