// @generated by protoc-gen-es v2.8.0 with parameter "target=ts"
// @generated from file whisk/protobuf/subscriptions_platfrom/api/v1/debug_api.proto (package whisk.protobuf.subscriptions_platform.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file whisk/protobuf/subscriptions_platfrom/api/v1/debug_api.proto.
 */
export const file_whisk_protobuf_subscriptions_platfrom_api_v1_debug_api: GenFile = /*@__PURE__*/
  fileDesc("Cjx3aGlzay9wcm90b2J1Zi9zdWJzY3JpcHRpb25zX3BsYXRmcm9tL2FwaS92MS9kZWJ1Z19hcGkucHJvdG8SKHdoaXNrLnByb3RvYnVmLnN1YnNjcmlwdGlvbnNfcGxhdGZvcm0udjEiIwoTR2V0RGVidWdJbmZvUmVxdWVzdBIMCgRuYW1lGAEgASgJIigKFEdldERlYnVnSW5mb1Jlc3BvbnNlEhAKCHJlc3BvbnNlGAEgASgJMpoBCghEZWJ1Z0FQSRKNAQoMR2V0RGVidWdJbmZvEj0ud2hpc2sucHJvdG9idWYuc3Vic2NyaXB0aW9uc19wbGF0Zm9ybS52MS5HZXREZWJ1Z0luZm9SZXF1ZXN0Gj4ud2hpc2sucHJvdG9idWYuc3Vic2NyaXB0aW9uc19wbGF0Zm9ybS52MS5HZXREZWJ1Z0luZm9SZXNwb25zZWIGcHJvdG8z");

/**
 * @generated from message whisk.protobuf.subscriptions_platform.v1.GetDebugInfoRequest
 */
export type GetDebugInfoRequest = Message<"whisk.protobuf.subscriptions_platform.v1.GetDebugInfoRequest"> & {
  /**
   * Just a string as an example of payload. Could be anything.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message whisk.protobuf.subscriptions_platform.v1.GetDebugInfoRequest.
 * Use `create(GetDebugInfoRequestSchema)` to create a new message.
 */
export const GetDebugInfoRequestSchema: GenMessage<GetDebugInfoRequest> = /*@__PURE__*/
  messageDesc(file_whisk_protobuf_subscriptions_platfrom_api_v1_debug_api, 0);

/**
 * @generated from message whisk.protobuf.subscriptions_platform.v1.GetDebugInfoResponse
 */
export type GetDebugInfoResponse = Message<"whisk.protobuf.subscriptions_platform.v1.GetDebugInfoResponse"> & {
  /**
   * Just a string as an example of payload. Could be anything.
   *
   * @generated from field: string response = 1;
   */
  response: string;
};

/**
 * Describes the message whisk.protobuf.subscriptions_platform.v1.GetDebugInfoResponse.
 * Use `create(GetDebugInfoResponseSchema)` to create a new message.
 */
export const GetDebugInfoResponseSchema: GenMessage<GetDebugInfoResponse> = /*@__PURE__*/
  messageDesc(file_whisk_protobuf_subscriptions_platfrom_api_v1_debug_api, 1);

/**
 * * Temporary service for debugging purposes.
 *
 * All the methods in this service require authentication via `Authorization` hearer.
 *
 * @generated from service whisk.protobuf.subscriptions_platform.v1.DebugAPI
 */
export const DebugAPI: GenService<{
  /**
   * Returns the debug information
   *
   * @generated from rpc whisk.protobuf.subscriptions_platform.v1.DebugAPI.GetDebugInfo
   */
  getDebugInfo: {
    methodKind: "unary";
    input: typeof GetDebugInfoRequestSchema;
    output: typeof GetDebugInfoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_whisk_protobuf_subscriptions_platfrom_api_v1_debug_api, 0);

