// @generated by protoc-gen-es v2.8.0 with parameter "target=ts,import_extension=js"
// @generated from file com/example/v1/hello_world_api.proto (package com.example.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file com/example/v1/hello_world_api.proto.
 */
export const file_com_example_v1_hello_world_api: GenFile = /*@__PURE__*/
  fileDesc("CiRjb20vZXhhbXBsZS92MS9oZWxsb193b3JsZF9hcGkucHJvdG8SDmNvbS5leGFtcGxlLnYxIiIKEkdldEdyZWV0aW5nUmVxdWVzdBIMCgRuYW1lGAEgASgJIicKE0dldEdyZWV0aW5nUmVzcG9uc2USEAoIZ3JlZXRpbmcYASABKAkyZwoNSGVsbG9Xb3JsZEFQSRJWCgtHZXRHcmVldGluZxIiLmNvbS5leGFtcGxlLnYxLkdldEdyZWV0aW5nUmVxdWVzdBojLmNvbS5leGFtcGxlLnYxLkdldEdyZWV0aW5nUmVzcG9uc2ViBnByb3RvMw");

/**
 * @generated from message com.example.v1.GetGreetingRequest
 */
export type GetGreetingRequest = Message<"com.example.v1.GetGreetingRequest"> & {
  /**
   * Just a string as an example of payload. Could be anything.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message com.example.v1.GetGreetingRequest.
 * Use `create(GetGreetingRequestSchema)` to create a new message.
 */
export const GetGreetingRequestSchema: GenMessage<GetGreetingRequest> = /*@__PURE__*/
  messageDesc(file_com_example_v1_hello_world_api, 0);

/**
 * @generated from message com.example.v1.GetGreetingResponse
 */
export type GetGreetingResponse = Message<"com.example.v1.GetGreetingResponse"> & {
  /**
   * Just a string as an example of payload. Could be anything.
   *
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message com.example.v1.GetGreetingResponse.
 * Use `create(GetGreetingResponseSchema)` to create a new message.
 */
export const GetGreetingResponseSchema: GenMessage<GetGreetingResponse> = /*@__PURE__*/
  messageDesc(file_com_example_v1_hello_world_api, 1);

/**
 * * Temporary service for debugging purposes.
 *
 *
 * @generated from service com.example.v1.HelloWorldAPI
 */
export const HelloWorldAPI: GenService<{
  /**
   * Returns the greeting
   *
   * @generated from rpc com.example.v1.HelloWorldAPI.GetGreeting
   */
  getGreeting: {
    methodKind: "unary";
    input: typeof GetGreetingRequestSchema;
    output: typeof GetGreetingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_com_example_v1_hello_world_api, 0);

